### ISSUE TITLE
Can't seem to install any version of this plugin in sylius 1.8 or 1.9

### ISSUE THREAD

**Issue by acornforth** [Setono/SyliusGiftCardPlugin#160] opened 2021-09-30 08:29 UTC
We are in the process of upgrading our sylius store from 1.8 to 1.9, our 1.8 branch is running on symfony 4.4, our 1.9 branch is running symfony 5.2.

Unfortunately I have not been able to install this plugin in either branch because the dependencies can't be resolved.

I started looking through the history of composer.json for th plugin and it seems that the dependencies have changes quite drastically between tagged releases, and it's not obvious which versions of sylius the plugin targets... some of the deps seem too new for S1.8 but then if i try to install it on S1.9, requires a lower version (^2.8) of the REST Bundle(v3.0.5) than our store (Sylius1.9.6)

**Comment by laurentdabbb** [comment] 2021-10-01 15:35
+1 Same problem here.

Sylius 1.9+ require "friendsofsymfony/rest-bundle" ^3.0 but your requirments specify only ^2.8

Your requirments seems to be too strict. You should just support from a specific version of Sylius and inherit from Sylius requirments.

Thx ;-)

**Comment by Roshyo** [comment] 2021-10-02 09:13
I think that for Sylius 1.9, you should use 0.12.x that is not yet tagged as a release as it is a WIP. But what's the problem for 1.8 @acornforth ?

**Comment by acornforth** [comment] 2021-10-06 13:19
![image (4)](https://user-images.githubusercontent.com/4586381/136210179-565668bd-495a-494c-a4c1-9e792a6931a8.png)

I tried with -W flag, but it wanted to upgrade a whole bunch of symfony and sylius packages.
I also tried just upgrading the knp-menu package, but then the next time, i jsut get a different package blocking the upgrade

**Comment by JulienLoison** [comment] 2021-11-03 10:56
I second @laurentdabbb's comment. Event on 0.12.x-dev, the requirements seems too strict. 

Few points that could be discussed : 
- sylius/sylius is in dev requirements while the Plugin Skeleton use it as a non-dev requirement
- setono/sylius-catalog-promotion-plugin is required as a dev dependency, why ? 
- some requirements (and dev requirements) are actually sylius/sylius requirements that could be delegated to sylius/sylius

Are there any reasons behind those choices (mainly the "not inheriting from sylius/sylius" part) ? Are we missing something here ?

Thanks !

**Comment by loevgaard** [comment] 2021-11-10 08:42
@acornforth: Could you try and use the `0.12.x` branch for 1.9 as @Roshyo suggests and give me a status?

**Comment by acornforth** [comment] 2021-11-15 08:52
Hi @loevgaard 

Sorry i haven't had a chance to test this for a while, my attention has been needed elsewhere. 

We still haven't got our main branch on to sylius 1.9 yet, we need to get some other features merged and do a big rebase before we get there, so here are the attempts i made on each branch.

Attempt on our sylius 1.9 branch:

![image](https://user-images.githubusercontent.com/4586381/141750071-dc1e57e9-f732-48d5-aff5-e56a91e0c906.png)

and on our 1.8 branch.

![image](https://user-images.githubusercontent.com/4586381/141750611-7596293d-741a-4ae6-aa6b-04554e1e12c7.png)

My first attempts to install were part of my initial research into whether this plugin is a viable option for us. And i think it could be, but meanwhile i have been tasked with some other jobs. Unfortunately i'm super busy working on another project at the moment. so i will not be able to really investigate whether there is an issue elsewhere in our composer dependencies until i am back looking at this again.

I'm just hoping that by the time i'm asked to actually install it, perhaps this issue may have been sorted ;)

**Comment by Roshyo** [comment] 2021-11-15 10:20
Can you please try on your 1.9 branch with `composer require setono/sylius-gift-card-plugin "^0.12.0" -W`

**Comment by acornforth** [comment] 2021-11-16 11:25
![image](https://user-images.githubusercontent.com/4586381/141977025-ad4b5116-2143-4e59-ba36-9542b19f1348.png)

**Comment by loevgaard** [comment] 2022-03-03 14:21
Hello everyone. This should have been fixed now in https://github.com/Setono/SyliusGiftCardPlugin/pull/199. Could any of you try to install the branch `0.11` before we release `0.11.8`?

**Comment by loevgaard** [comment] 2022-03-04 09:59
Will close this as the fix in #199 was confirmed in another issue, namely #179. Please let me know if you have any other problems :)

**Closed as completed by loevgaard** 2022-03-04 09:59 UTC

**Comment by acornforth** [comment] 2022-03-07 10:17
@loevgaard thanks, I will do that.

Have been working on something else for a while now, but i will check this all out when i come back to this in due course.
